## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
cp-zookeeper:
  enabled: false

## ------------------------------------------------------
## Kafka
## ------------------------------------------------------
cp-kafka:
  enabled: false

## ------------------------------------------------------
## Schema Registry
## ------------------------------------------------------
cp-schema-registry:
  enabled: false

## ------------------------------------------------------
## REST Proxy
## ------------------------------------------------------
cp-kafka-rest:
  enabled: false

## ------------------------------------------------------
## Kafka Connect
## ------------------------------------------------------
cp-kafka-connect:
  resources:
    requests:
      cpu: 2048m
      memory: 1Gi
    limits:
      cpu: 3072m
      memory: 2Gi
  kafka:
    bootstrapServers: "PLAINTEXT://kafka-headless:9092"

  cp-schema-registry:
    url: "sr-schema-registry:8081"


## ------------------------------------------------------
## KSQL Server
## ------------------------------------------------------
cp-ksql-server:
  enabled: false