resources:
  requests:
    cpu: 2048m
    memory: 4Gi
  limits:
    cpu: 3072m
    memory: 6Gi


kafkaHeapOptions: "-Xmx4G -Xms1G"

readinessProbe:
  initialDelaySeconds: 60

persistence:
  size: "10Gi"

zookeeper:
  resources:
    requests:
      cpu: 2048m
      memory: 2Gi
    limits:
      cpu: 3072m
      memory: 4Gi
